### ISSUE TITLE
undefined 'fromColumnName'

### ISSUE THREAD

**Issue by mihaidma** [senecajs/seneca-postgres-store#87]
On gitter one user reported an undefined fromColumnName issue. This is the text:

when running unit test with seneca-postresql-store, I got these error
```
1) user profile test happy:
     Uncaught TypeError: Cannot read property 'fromColumnName' of undefined
      at Object.internals.transformDBRowToJSObject (node_modules/seneca-postgresql-store/lib/postgresql-store.js:299:26)
      at node_modules/seneca-postgresql-store/lib/postgresql-store.js:184:35
      at .<anonymous> (node_modules/seneca-postgresql-store/lib/postgresql-store.js:123:18)
```
I check source and need to work around to fix this issue
```
internals.transformDBRowToJSObject = function (row) {
    var obj = {}
   // here where I work around 
    if (StandardQuery == null) {
      StandardQuery = seneca.export('standard-query/utils')
    }
    for (var attr in row) {
      if (row.hasOwnProperty(attr)) {
        obj[StandardQuery.fromColumnName(attr)] = row[attr]
      }
    }
    return obj
  }
```

**Comment by tswaters** [comment]
We're getting this if we attempt to query the database shortly after startup.  We have a `seneca-mesh` setup and when all services fire `ready` after having joined the mesh, they will attempt to start talking to eachother, which ends up asking postgres for queries... this is where it blows up.

The posted fix works fine -- but it seems to me, the plugin should only emit that it is ready after it has been properly initialized and can accept queries.  I tried to work around it by putting the use/ready bit inside the plugin initialization but I got timeouts and massive dumps of red text to console.

**Comment by matiger** [comment]
If anybody has the same problem, and does not want to fork the repo, could try do increase cpu/memory, which fixed the issue for us.
